### ISSUE TITLE
bug: generated `schema.json` file includes `null` values as `cType`

### ISSUE THREAD

**Issue by AndreasDemenagas** [sufst/can-defs#3]
### Description
The `schema.json` file generated includes fields with `null` as the `cType` value. 

### Steps To Reproduce
1. Run the code generation.
2. Observe the generated `schema.json` file. 

### Expected Behaviour
The `cType` field should always be present as it is used in the intermediate-server to unpack and build the sensor configuration.

**Comment by t-bre** [comment]
The culprit seems to be the PM100DZ firmware information, which is generated as:

```json
"M174_Firmware_Info": {
    "id": 17,
    "header": [
      {
        "name": "valid_bitfield",
        "cType": "H"
      },
      {
        "name": "epoch",
        "cType": "d"
      }
    ],
    "body": [
      {
        "name": "INV_Project_Code_EEP_Ver",
        "cType": "H"
      },
      {
        "name": "INV_SW_Version",
        "cType": "H"
      },
      {
        "name": "INV_DateCode_MMDD",
        "cType": null
      },
      {
        "name": "INV_DateCode_YYYY",
        "cType": null
      }
    ]
  },
```

It seems that the current method of determining the `cType` by parsing the generated source code does not work for `INV_DateCode_MMDD` and `INV_DateCode_YYYY`.

**Comment by t-bre** [comment]
Looking at what gets generated, the struct fields are `uint16_t inv_date_code_mmdd` and `uint16_t inv_date_code_yyyy`. There is an underscore in `date_code` in the generated structs, but no underscore in the name of the signal which causes the source code parsing not to find the signal's corresponding struct field.

Printing the corresponding signal names gives:
```text
INV_DateCode_MMDD
INV_DateCode_YYYY
```
The names are the same when opening the PM100DZ DBC in Kvaser Database Editor.

Not sure if this is an issue with the `cantools` library, or a bug in our code (probably the latter).

**Comment by t-bre** [comment]
Looking at the `cantools` library, in [`c_source.py`](https://github.com/cantools/cantools/blob/master/cantools/database/can/c_source.py) there are the following lines of code:

```python
class Signal(object):

    def __init__(self, signal):
        self._signal = signal
        self.snake_name = camel_to_snake_case(self.name)
```

```python
def camel_to_snake_case(value):
    value = re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', value)
    value = re.sub(r'(_+)', '_', value)
    value = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', value).lower()
    value = _canonical(value)

    return 
```

Because `DateCode` is two words in `PascalCase` an underscore is inserted between the words when generating `snake_name` which is used as the name of the struct field in the generated C code. The code we use to search for the signal name in the C code assumes that the name of the struct field is just the signal name in lower case which is incorrect.

I see two solutions:
- Use the `camel_to_snake_case` code above to generate the correct struct field name from the signal name when the search is done.
- Instead of searching the generated code for the `cType`, use the properties of the `Signal` object. I much prefer this solution.

**Comment by t-bre** [comment]
Unfortunately it seems the second solution is not quite as simple because the `Signal` class above is not the same as `cantools.database.can.Signal`. The latter does not have the properties necessary to determine the `cType`.

For now, will go for the first solution.
